### ISSUE TITLE
[1.12.2] Latest Mo'Glowstone crashes with world gen set to false

### ISSUE THREAD

**Issue by kwpugh** [MasterGeneral156/MoGlowstone-Mod#1]
Mo-Glowstone-1.12.2-1.5.2.jar

Using the new config option to turn off flowstone ore causes crash.

Report:  https://gist.github.com/kwpugh/ad43bbd8a4adf70e67b6315d22983c62

**Comment by MasterGeneral156** [comment]
Pushing 1.5.3 now. Waiting on CF approval. Thanks for reporting!
