### ISSUE TITLE
Config options for worldgen and crafting recipes

### ISSUE THREAD

**Issue by angelnc1989** [MasterGeneral156/MoGlowstone-Mod#2]
Please add config options to disable worldgen features (each seperatly) and to disable crafting recipes (especially the Glowstone Dust one). I would like to include your mod in my modpacks, but without the ability to configure things, it's just not possible.

**Comment by MasterGeneral156** [comment]
Check the latest build on Curse (uploading/pending approval as we speak) for the world generation options.
I don't have a good way to have recipes toggleable using the json system, however. So you'll have to use MineTweaker for that. :(
