### ISSUE TITLE
[Suggestion]: Chisel Support?

### ISSUE THREAD

**Issue by Z-Tunic** [MasterGeneral156/MoGlowstone-Mod#3]
Regular Glowstone Blocks can be chisled with the Chisel mod, was wondering if it could be possible for the colored Glowstone in this mod to get chisel support & connected textures, which is CTM for short?

**Comment by fallenhunter1** [comment]
I will bump this and raise my hand in support.

Thanks.

**Comment by MasterGeneral156** [comment]
Bare with me, been out of the loop since the 1.12 days.... I'll look into ReChisel Compat here. Looks fairly straightforward.
ht
