### ISSUE TITLE
1.14.4 server crash on startup

### ISSUE THREAD

**Issue by Wissi** [MasterGeneral156/MoGlowstone-Mod#4]
Awesome work.

We tried to add you mod to our current server and will crash during startup.
Might be a mod incompatibility issue, but here is the full [log](https://gist.github.com/Wissi/94ab2828875980e297f1b9a0ed9a180d).
And the crash log [here](https://gist.github.com/Wissi/893d5c60cdda790dd00aec60f1e7b2ff).

Hope it helps and here is something on your end to make it work.

Thanks.

**Comment by MasterGeneral156** [comment]
> [05Sep2019 03:26:53.254] [Server thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §emoglowstone§r requires §6ctdcore§r §o2 or above§r
§7Currently, §6ctdcore§r§7 is §o§nnot installed

Can you try installing CTD Core for 1.14.4? It looks like that is the issue.
https://www.curseforge.com/minecraft/mc-mods/ctd-core/files/2768442

**Comment by Wissi** [comment]
YES !
Wow being late and not reading does that. 
Working perfectly fine on client and server.
Will include in all our modpacks.

Thank you so much, awesome mod.
