### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by ghost** [MasterGeneral156/MoGlowstone-Mod#5]
It would appear that localization was lost in v1.5.7 for 1.12.2. Not sure if it was missing prior, just noticed it tonight. This applies to ALL blocks from the mod.

**Comment by MasterGeneral156** [comment]
I noticed this in a new modded world I started. I'll be looking into it tonight! Thanks!

**Comment by MasterGeneral156** [comment]
Appears I got it fixed. Update has been uploaded to Curseforge, should be accepted here soon. Thanks man!
