### ISSUE TITLE
Disable from nether world gen.

### ISSUE THREAD

**Issue by SnakekillerX** [MasterGeneral156/MoGlowstone-Mod#6]
I like the coloured glowstones however I dislike the coloured nether.
Can you make an option to disable the coloured variants from world gen please?

Thanks

**Comment by MasterGeneral156** [comment]
What version are you using? I really thought it was a config option. I'll confirm when I get home.

**Comment by SnakekillerX** [comment]
1.12.2

**Comment by SnakekillerX** [comment]
Looks like its spawning in the overworld too actually.  Any way to stop world gen spawning?

**Comment by MasterGeneral156** [comment]
I apologize about the delay:  
There appears to be  config options to disable the world generation already. (`config\ctd\moglowstone.cfg`)  
I added a config option to disable Albedo integration (The mod that makes RGB lighting possible in Minecraft?)  
  
The only thing that spawn in the overworld _should_ just be the Glowstone Ore. I can confirm, in a clean dev and heavily modded environments, the only Overworld world-gen our mod has is the Glowstone Ore.
  
I rolled that config option into version 1.12.2-1.5.9; you can get it from [Curse now](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone/files/2949745)!  
  
I apologize if I misunderstood what you mean.

**Comment by SnakekillerX** [comment]
Hey I found it, I wouldn't have guessed to look in that folder.  I have a very large mod pack so things can get really hard to find if the name of the folder or config doesn't match the mod name.

Appreciate your help.

**Comment by MasterGeneral156** [comment]
Hey its all good man. Most of my mods will have their config folder in there. I felt it kinda fit to put this one there, too? Idk. :D
