### ISSUE TITLE
No light being produced

### ISSUE THREAD

**Issue by Breadabix** [MasterGeneral156/MoGlowstone-Mod#7]
Im having an issue using this mod in 1.16.5, no light is being produced by the custom glowstone. Is there any known incompatilities ive missed while looking for fixes or is this a new issue?

**Comment by MasterGeneral156** [comment]
Sorry for the delay! Its very likely just broken with Forge updates. I'll take a look when I get some time here this weekend :)

**Comment by Breadabix** [comment]
I realised literally 30 mins ago I missed an obvious possible incompatibility, it seems this is only an issue with optifine installed.

Edit: It seems its not just this mod affected by optifine, glowstone microblocks and having multiple torches in the same block stop producing light with optifine, so Im guessing its an optifine issue and nothing specifically to do with this mod. I have created a bug report on optifines github, but do you think there is anything to do this end that might fix it?
