### ISSUE TITLE
1.20.1 Missing Texture

### ISSUE THREAD

**Issue by xd4rkzghost01** [MasterGeneral156/MoGlowstone-Mod#9]
Hello there ! 
I'm "building" my own pack and was adding this mod but encounter a little issue. The Orange Glowstone Block have a texture missing, and it was the only one. Even the Orange Lamp is good.

MC 1.20.1
Forge 47.2.6
Mo'Glowstone 1.20.1 - 2.4.3
![2024-02-14_03 27 15](https://github.com/MasterGeneral156/MoGlowstone-Mod/assets/63568312/45e32ce8-96f4-46b3-adf6-14d53452fe96)

**Comment by MasterGeneral156** [comment]
I'll take a look when I get off work this afternoon. On Feb 14, 2024 3:32 AM, xd4rkzghost01 ***@***.***> wrote:
Hello there !
I'm "building" my own pack and was adding this mod but encounter a little issue. The Orange Glowstone Block have a texture missing, and it was the only one. Even the Orange Lamp is good.
2024-02-14_03.27.15.png (view on web)
